= Dockerfile

Docker image to use `terraform` from a container. The image contains other software which is needed by other Terraform provideres as well.

== Overview

Run `terraform` commands without installing Terraform onto any machine.
The only dependency is link:https://www.docker.com[Docker]. The image ships with some
addtional software like the link:https://bitwarden.com/help/cli[Bitwarden CLI] which
is needed for the link:https://registry.terraform.io/providers/maxlaverse/bitwarden/latest/docs[Terraform Bitwarden Provider]
to work.

The image is published to DockerHub as link:https://hub.docker.com/r/sommerfeldio/terraform[`sommerfeldio/terraform`]

This project is used for my
link:https://github.com/sebastian-sommerfeld-io/configs/actions/workflows/configure-github.yml[Global: Apply Github Configuration]
pipeline. The pipeline ensures a consistent Github configuration and all configuration
for all repositories.

== How to use this image

Use this command to run the image as a non-root user (pass the current user of the
host into the container). This is tested on Ubuntu 22.04. This example needs three
environment variables `TV_VAR_bw_*` for the Bitwarden CLI (which is used by the
link:https://registry.terraform.io/providers/maxlaverse/bitwarden/latest/docs[Terraform Bitwarden Provider])
to work. The `GITHUB_TOKEN` environment variable is needed for the
link:https://registry.terraform.io/providers/integrations/github/latest/docs[Terraform Github Provider].
Adjust the environment variables according to your needs.

[source, bash]

----
BW_CLIENT_ID="bitwarden-data"
BW_CLIENT_SECRET="bitwarden-data"
BW_MASTER_PASS="bitwarden-data"

docker run --rm \
--volume /etc/passwd:/etc/passwd:ro \
--volume /etc/group:/etc/group:ro \
--user "$(id -u):$(id -g)" \
--volume /etc/timezone:/etc/timezone:ro \
--volume /etc/localtime:/etc/localtime:ro \
--volume "$(pwd):$(pwd)" \
--workdir "$(pwd)" \
--env "GITHUB_TOKEN=$TOKEN" \
--env "TF_VAR_bw_client_id=$BW_CLIENT_ID" \
--env "TF_VAR_bw_client_secret=$BW_CLIENT_SECRET" \
--env "TF_VAR_bw_password=$BW_MASTER_PASS" \
sommerfeldio/terraform:latest apply -auto-approve
----

CAUTION: Keep in mind that storing passwords in variables like this is not a
recommended way to handle your secrets.
