= Dockerfile

Docker image for jq.

== Overview

The link:https://hub.docker.com/r/sommerfeldio/jq[`sommerfeldio/jq`]
image ships with link:https://stedolan.github.io/jq[jq] which is a lightweight and
flexible command-line JSON processor.

== About the tags and versions

include::ROOT:partial$/docker-tag-strategy.adoc[]

== See also

For Docker image sources, see https://github.com/sommerfeld-io/docker-images/tree/main/src/main.
