= Dockerfile

Docker image for jq.

== Overview

The link:https://hub.docker.com/r/sommerfeldio/jq[`sommerfeldio/jq`]
image ships with link:https://stedolan.github.io/jq[jq] which is a lightweight and
flexible command-line JSON processor.
