= Dockerfile

...

== Overview

...
todo ... write description and brief (above)

== Prerequisites

This image has been developed and tested with Docker version 24.0.2 on top of Ubuntu 22.10.

== About the tags and versions

This Docker image follows a tagging convention based on semantic versioning. Each
stable version of the image is tagged with a specific semantic version (e.g.
`:v0.2.0`), while the `:latest` tag always points to the most recent stable
version.

Unstable versions are marked with a suffix (`-alpha.0`, `-beta.0` or `-rc.0`).
These versions usually are used for development or testing purposes. These versions
are not recommended for production use. `:latest` never points to an unstable
pre-release.

The image may have a `:main` tag, which represents an unstable build. These versions
come from CI builds and/or nightly builds and are useful for continuous integration
and testing purposes. The `:main` tag is never meant for production use and may
contain experimental features or unresolved issues.

== How to use this image

[source, bash]

----
docker build -t local/qodana:dev .

touch qodana.sarif.json && docker run --rm -it -p 8080:8080 \
--volume "$(pwd):/data/project" \
--volume "$(pwd)/qodana.sarif.json:/data/results/qodana.sarif.json:rw" \
local/qodana:dev \
--property=idea.suppressed.plugins.id=com.intellij.gradle,org.jetbrains.plugins.gradle \
--show-report
----

Creating the `qodana.sarif.json` file is needed to allow mounting the file into the container.
Without this, the report stays hidden in the container and is not available for e.g. uploading
to GitHub Code scanning alerts. Without touching the file first, Docker (as per its default
behavior) creates a folder which causes Qodana to crash.

It is recommended to add the `qodana.sarif.json` to your `.gitignore` file.

To use the image in GitHub Actions workflows, omitt the `--show-report` flag.

== See also

* Official Qodana docs \-> https://www.jetbrains.com/help/qodana/getting-started.html
* About the base image \-> https://www.jetbrains.com/help/qodana/qodana-jvm-community-docker-readme.html
* IntelliJ AsciiDoc Plugin docs \-> https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/validation-cicd.html
