= Dockerfile

Docker image that ships with the folderslint npm module.

== Overview

The link:https://hub.docker.com/r/sommerfeldio/folderslint[`sommerfeldio/folderslint`]
image is a utility Docker image used in Github Actions workflows to validate the
directory structure of a project. The image ships with
link:https://www.npmjs.com/package/folderslint[folderslint].

== How to use this image
To use the image run the following command.

[source, bash]

----
docker run -it --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest
----

=== Use in a Github Actions workflow

[source, yml]

----
lint-folders:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3
- name: Run folderslint in container
run: docker run -i --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest
----
