= Dockerfile

Dockerfile for generating AsciiDoc Documentation based on inline documentation.

== Overview

This Dockerfile is designed to generate AsciiDoc documentation for a
specific Antora module based on inline documentation from Dockerfiles, Bash scripts,
and GitHub Actions workflows.

The generated documentation provides a comprehensive guide for developers and users,
enhancing the understanding of the codebase and facilitating smoother collaboration.

NOTE: This image is intentionally running as root to make sure it can be used inside
Github Actions workflows without permission errors.

This image is link:https://hub.docker.com/r/sommerfeldio/source2docs[published to DockerHub]
as `sommerfeldio/source2docs`.

== About the tags and versions

include::ROOT:partial$/docker-tag-strategy.adoc[]

== How to use this image
To use the image run the following command from a bash file.

[source, bash]

----
# Run with default "docs" folder in project root
docker run --rm --user "$(id -u):$(id -g)"  --volume /etc/timezone:/etc/timezone:ro  --volume /etc/localtime:/etc/localtime:ro  --volume "$(pwd):/project"  --workdir "/project"  sommerfeldio/source2docs:latest

# Override the docs folder path
docker run --rm --user "$(id -u):$(id -g)"  --volume /etc/timezone:/etc/timezone:ro  --volume /etc/localtime:/etc/localtime:ro  --volume "$(pwd):/project"  --workdir "/project"  sommerfeldio/source2docs:latest components/docs
----

NOTE: Run this image from the root of your project. Do not change the volume bind from
`/project` to anything else because the scripts inside the action expect this folder
to exist and to contain your projects data.

== See also

The base image is link:https://hub.docker.com/r/bitnami/git[`bitnami/git`]. See
link:https://docs.bitnami.com/tutorials/understand-rolling-tags-containers[Bitname Docs]
for details on Bitnami's tagging system and how you can use it to identify different
versions of its Docker container images.

The xref:AUTO-GENERATED:src/main/docker/source2docs/entrypoint-sh.adoc[src/main/docker/source2docs/entrypoint.sh]
script serves as the entrypoint for this Docker image.

For Docker image sources, see https://github.com/sommerfeld-io/docker-images/tree/main/src/main.
